/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CharactersRouteImport } from './routes/characters'
import { Route as CharactersIndexRouteImport } from './routes/characters/index'
import { Route as CharactersIdRouteImport } from './routes/characters/$id'

const CharactersRoute = CharactersRouteImport.update({
  id: '/characters',
  path: '/characters',
  getParentRoute: () => rootRouteImport,
} as any)
const CharactersIndexRoute = CharactersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CharactersRoute,
} as any)
const CharactersIdRoute = CharactersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CharactersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/characters': typeof CharactersRouteWithChildren
  '/characters/$id': typeof CharactersIdRoute
  '/characters/': typeof CharactersIndexRoute
}
export interface FileRoutesByTo {
  '/characters/$id': typeof CharactersIdRoute
  '/characters': typeof CharactersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/characters': typeof CharactersRouteWithChildren
  '/characters/$id': typeof CharactersIdRoute
  '/characters/': typeof CharactersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/characters' | '/characters/$id' | '/characters/'
  fileRoutesByTo: FileRoutesByTo
  to: '/characters/$id' | '/characters'
  id: '__root__' | '/characters' | '/characters/$id' | '/characters/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  CharactersRoute: typeof CharactersRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/characters': {
      id: '/characters'
      path: '/characters'
      fullPath: '/characters'
      preLoaderRoute: typeof CharactersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/characters/': {
      id: '/characters/'
      path: '/'
      fullPath: '/characters/'
      preLoaderRoute: typeof CharactersIndexRouteImport
      parentRoute: typeof CharactersRoute
    }
    '/characters/$id': {
      id: '/characters/$id'
      path: '/$id'
      fullPath: '/characters/$id'
      preLoaderRoute: typeof CharactersIdRouteImport
      parentRoute: typeof CharactersRoute
    }
  }
}

interface CharactersRouteChildren {
  CharactersIdRoute: typeof CharactersIdRoute
  CharactersIndexRoute: typeof CharactersIndexRoute
}

const CharactersRouteChildren: CharactersRouteChildren = {
  CharactersIdRoute: CharactersIdRoute,
  CharactersIndexRoute: CharactersIndexRoute,
}

const CharactersRouteWithChildren = CharactersRoute._addFileChildren(
  CharactersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  CharactersRoute: CharactersRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
