/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersRouteImport } from './routes/users'
import { Route as AnotherRouteRouteImport } from './routes/anotherRoute'

const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AnotherRouteRoute = AnotherRouteRouteImport.update({
  id: '/anotherRoute',
  path: '/anotherRoute',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/anotherRoute': typeof AnotherRouteRoute
  '/users': typeof UsersRoute
}
export interface FileRoutesByTo {
  '/anotherRoute': typeof AnotherRouteRoute
  '/users': typeof UsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/anotherRoute': typeof AnotherRouteRoute
  '/users': typeof UsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/anotherRoute' | '/users'
  fileRoutesByTo: FileRoutesByTo
  to: '/anotherRoute' | '/users'
  id: '__root__' | '/anotherRoute' | '/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AnotherRouteRoute: typeof AnotherRouteRoute
  UsersRoute: typeof UsersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anotherRoute': {
      id: '/anotherRoute'
      path: '/anotherRoute'
      fullPath: '/anotherRoute'
      preLoaderRoute: typeof AnotherRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  AnotherRouteRoute: AnotherRouteRoute,
  UsersRoute: UsersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
